In [30]:
import numpy as np
a = np.random.randint(1,30,(5,6))
print(a)

[[16 14 14  3 20 23]
 [25  7 10 25 18 28]
 [29  3 15  8 27 23]
 [26 11 29 17 17 18]
 [11 10 27 12  1  4]]


In [31]:
bool_arr = a > 20
print(bool_arr)


[[False False False False False  True]
 [ True False False  True False  True]
 [ True False False False  True  True]
 [ True False  True False False False]
 [False False  True False False False]]


In [32]:
ans = a[bool_arr]
print(ans)

[23 25 25 28 29 27 23 26 29 27]


In [33]:
b = a

In [34]:
b[bool_arr] = 100
print(b)

[[ 16  14  14   3  20 100]
 [100   7  10 100  18 100]
 [100   3  15   8 100 100]
 [100  11 100  17  17  18]
 [ 11  10 100  12   1   4]]


In [35]:
c = np.random.randint(1,10,(2,2))
print(c)

[[5 3]
 [1 6]]


In [36]:
c_bool = np.array([[True,False],[False,True],[True,True]])
print(c_bool)

[[ True False]
 [False  True]
 [ True  True]]


In [19]:
# print(c[c_bool])

In [37]:
print(b)

[[ 16  14  14   3  20 100]
 [100   7  10 100  18 100]
 [100   3  15   8 100 100]
 [100  11 100  17  17  18]
 [ 11  10 100  12   1   4]]


In [38]:
bool_arr = b[:, 4] == 100
print(bool_arr)

[False False  True False False]


In [39]:
b[bool_arr,4] = 99
print(b)

[[ 16  14  14   3  20 100]
 [100   7  10 100  18 100]
 [100   3  15   8  99 100]
 [100  11 100  17  17  18]
 [ 11  10 100  12   1   4]]


sort by column

In [62]:
import numpy as np
a = np.arange(21,1,-1).reshape(4,5)

sorted_array = a[np.argsort(a[:,4])]
sorted_array

array([[ 6,  5,  4,  3,  2],
       [11, 10,  9,  8,  7],
       [16, 15, 14, 13, 12],
       [21, 20, 19, 18, 17]])

In [66]:
import numpy as np
a = np.arange(21,1,-1)
a = a.reshape(4,5)
a = a[a[:,1].argsort()]
a


array([[ 6,  5,  4,  3,  2],
       [11, 10,  9,  8,  7],
       [16, 15, 14, 13, 12],
       [21, 20, 19, 18, 17]])