In [2]:
import numpy as np
x = np.random.randint(1,10,(3,3))
y = np.random.randint(1,10,(3,3))
print(x)
print(y)

[[6 9 9]
 [5 2 7]
 [9 4 1]]
[[8 6 3]
 [2 8 9]
 [2 4 3]]


In [3]:
ans = x-y
print(ans)

[[-2  3  6]
 [ 3 -6 -2]
 [ 7  0 -2]]


In [6]:
x = np.random.randint(1,10,(3,3))
y = np.random.randint(1,10,(3))

In [7]:
ans = x-y
print(ans)

[[ 6 -2  4]
 [ 1 -2  0]
 [ 2 -5  0]]


In [16]:
x = np.random.randint(1,10,(3,2))
y = np.random.randint(1,10,(2,3))
y = np.transpose(y)


In [17]:
ans = x-y
print(ans)

[[ 4 -1]
 [ 2 -3]
 [-2 -1]]
