In [1]:
import numpy as np
a = [1,2,3]
b = np.array(a)
print(b)
print(type(b))

[1 2 3]
<class 'numpy.ndarray'>


In [3]:
a = [1,2,3,'3',3.4]
b = np.array(a,dtype = int)
b

array([1, 2, 3, 3, 3])

In [4]:
a = [1,2,3,'4',4.5]
b = np.array(a*3)
print(b)

['1' '2' '3' '4' '4.5' '1' '2' '3' '4' '4.5' '1' '2' '3' '4' '4.5']


In [5]:
b = np.ones(3,dtype = int)
b

array([1, 1, 1])

In [7]:
b = np.zeros(3,dtype = int)
b

array([0, 0, 0])

In [9]:
b = np.ones((2,3),dtype = int)
b

array([[1, 1, 1],
       [1, 1, 1]])

In [10]:
b = np.zeros((3,4),dtype = int)
b

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [15]:
b = np.full((3,3),5,dtype = float)
b

array([[5., 5., 5.],
       [5., 5., 5.],
       [5., 5., 5.]])

In [32]:
h= np.empty([2, 3,],dtype = int,order= 'C')
h

array([[         0, 1075052544,          0],
       [1075052544,          0, 1075052544]])

In [36]:
b = np.arange(10)
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [40]:
b = np.linspace(2,10)
b
print(b[3]-b[2])
print(b[9]-b[8])

0.16326530612244916
0.16326530612244916


In [43]:
b = np.linspace(2,10,5,dtype = int,endpoint = False)
b

array([2, 3, 5, 6, 8])

In [45]:
b = np.identity(3)
b

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [48]:
b= np.eye(3,4)
b

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [52]:
b=np.random.rand(4)
b

array([0.34916154, 0.48460036, 0.5348682 , 0.6445184 ])

In [54]:

b=np.random.rand(3,4)
b

array([[0.46257652, 0.81219141, 0.07106817, 0.85754694],
       [0.70566102, 0.86717663, 0.08696582, 0.01494312],
       [0.87970369, 0.74507837, 0.73357007, 0.74625639]])

In [55]:
b=np.random.rand(10)*10
b

array([1.53454632, 5.41129435, 6.79920355, 4.33326255, 9.07282701,
       4.42237572, 8.88548786, 8.72971613, 4.39790793, 3.220751  ])

In [60]:
b= np.random.randint( 2, size=10, dtype=int)
b

array([0, 1, 0, 0, 1, 1, 1, 1, 1, 1])

NumPy 2D array

In [6]:
import numpy as np
a = np.arange(1,10).reshape(3,3)
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Numpy 0s and 1s

In [1]:
import numpy as np
a = [0,0,0,0,0,0,0,0,0,0]
a[4] = 1
b = np.array(a)
for i in b:
    print(i,end=' ')

0 0 0 0 1 0 0 0 0 0 

NumPy Inclusive 

In [5]:
import numpy as np
a = np.linspace(9,49)
for i in a:
    print(i,end=' ')

9.0 9.816326530612244 10.63265306122449 11.448979591836736 12.26530612244898 13.081632653061224 13.89795918367347 14.714285714285715 15.53061224489796 16.346938775510203 17.163265306122447 17.979591836734695 18.79591836734694 19.612244897959183 20.42857142857143 21.244897959183675 22.06122448979592 22.877551020408163 23.693877551020407 24.510204081632654 25.3265306122449 26.142857142857142 26.95918367346939 27.775510204081634 28.591836734693878 29.408163265306122 30.224489795918366 31.040816326530614 31.857142857142858 32.673469387755105 33.48979591836735 34.30612244897959 35.12244897959184 35.93877551020408 36.755102040816325 37.57142857142857 38.38775510204081 39.20408163265306 40.02040816326531 40.83673469387755 41.6530612244898 42.46938775510204 43.285714285714285 44.10204081632653 44.91836734693878 45.734693877551024 46.55102040816327 47.36734693877551 48.183673469387756 49.0 

In [7]:
import numpy as np
a = np.eye(5,6,dtype= int)
a

array([[1, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0],
       [0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 1, 0]])

In [12]:
import numpy as np
a = np.linspace(0,5,num=10)
for i in a:
    if i == 0 or i == 5:
        continue
    else:
        print(round(i,2))

0.56
1.11
1.67
2.22
2.78
3.33
3.89
4.44


Print Elements

In [24]:
import numpy as np
input_ = np.arange(1,21,1)
input_= input_.reshape(4,5)
print(input_)
print()
for i in input_[2,0:3]:
    print(i,end=" ")
print()
print()
for i in input_[1:4,3]:
    print(i)
print()
for i in input_[2:4,0:5]:
    print(i)
print()
for i in input_[1:3,1:3]:
    print(i)


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]

11 12 13 

9
14
19

[11 12 13 14 15]
[16 17 18 19 20]

[7 8]
[12 13]


Non-Zero element
---------------------------
Find indices of non-zero elements from the array [1,2,0,0,4,0] ?
Print the index of non-zero elements.

In [31]:
import numpy as np
a = np.array([1,2,0,0,4,0])
a= np.where(a!=0)
for i in a[0]:
    print(i,end=' ')

0 1 4 

Multiples of 3
-------------------
Given an integer array of size 10. Print the index of elements which are multiple of 3.
Note: Generate the following array
array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])
Print the index of elements.

Output Format :
index1 index2 index3 ... 

In [39]:
import numpy as np
a = np.array([1,3,5,7,9,11,13,15,17,19])
inp = np.where(a%3 == 0)
for i in inp[0]:
    print(i,end=' ')

1 4 7 

In [59]:
import numpy as np
a = np.arange(1,11,1)
# print(a)
i = np.where(a%2!=0,-1,a)
i


array([-1,  2, -1,  4, -1,  6, -1,  8, -1, 10])

In [63]:
import numpy as np
a = np.array([11,2,13,4,15,6,27,8,19])
maxElement = np.max(a)
i = np.where(maxElement == a,0,a)
i

array([11,  2, 13,  4, 15,  6,  0,  8, 19])

In [68]:
import numpy as np
a = np.arange(1,11,1)
i = np.where((a>2) & (a<9), a*-1, a)
i

array([ 1,  2, -3, -4, -5, -6, -7, -8,  9, 10])

Height

In [80]:
## Open and read data file as specified in the question
## Print the required output in given format
import numpy as np
age=np.array([15,17,19,20,14,21,16,19,13,20,22,23,21,16,18,19,20,15,17,18])
height=np.array([156,144,180,162,152,157,154,155,151,150,158,179,126,182,183,154,159,160,172,149])
k = []
l = []
i = 0
h = np.where(height > 155)
for i in range(len(h[0])):
    print(age[i], height[i])



15 156
17 144
19 180
20 162
14 152
21 157
16 154
19 155
13 151
20 150
22 158
